//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS390.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS390.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS-125-00  Comp Sci I      BObama     1.00 30  2 21202 08253 
        ///CS-225-00  Comp Sci II     BObama     1.00 20  1 21242 
        ///CS-355-00  Adv OOP         BObama     1.00 15  1 21282 
        ///MTH-135-01 Calculus I      MRomney    1.00 24  1 15253 
        ///MTH-135-02 Calculus I      MRomney    1.00 20  1 15223 
        ///MTH-145-00 Calculus II     MRomney    1.00 112 2 12162 04302 .
        /// </summary>
        internal static string CourseDatabase {
            get {
                return ResourceManager.GetString("CourseDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JBiden     2  CS-125-00  F13 1.00 B-  BUS-235-01 S14 0.50 B 
        ///PRyan      3  CS-125-00  F13 1.00 A   CS-225-00  F14 1.00 N   CS-235-00  S15 1.00 N 
        ///FLWright   3  CS-125-00  F13 1.00 S   CS-125-00  S14 1.00 B   MTH-135-00 S14 1.00 A .
        /// </summary>
        internal static string CourseHistoryDatabase {
            get {
                return ResourceManager.GetString("CourseHistoryDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dashboard_Background {
            get {
                object obj = ResourceManager.GetObject("Dashboard Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoginScreenBackground {
            get {
                object obj = ResourceManager.GetObject("LoginScreenBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchIcon {
            get {
                object obj = ResourceManager.GetObject("searchIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JBiden     Delaware   Joe             Robinette       Biden           BObama    
        ///MRomney    Mass       Willard         Mitt            Romney          faculty   
        ///BObama     Illinois   Barack          Hussein         Obama           faculty   
        ///PRyan      Cheese     Paul            Davis    	      Ryan            MRomney   
        ///Voter      USA        Jane            Quincy          Public          admin     
        ///CVN        mathsci    Calvin          Security        Van Niewaal     admin     
        ///FLWright   Taliesin  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserDatabase {
            get {
                return ResourceManager.GetString("UserDatabase", resourceCulture);
            }
        }
    }
}
